## A project name for naming summary files
project: "test"

## Input files
sample_sheet: "test_data/test_sample_sheet.csv"
outdir: "test_out"

## Busco lineage: use full lineage name: xxx_odb12
busco_lineage: "fungi_odb12"

## Settings
# minimum number of samples in a gene tree required to build a tree
# since astral4 can summarize gene trees with missing taxa
# Can't be lower than 4
minimum_sample_n: 4

## Resources and parallel configs
cpus: 40
cpus_per_compleasm: 10
n_parallele_mafft: 40
n_parallele_iqtree: 40
astral: "astral4"
